[workspace]
resolver = "2"
members = [
    "cli",
    "api-server", 
    "shared-lib"
]

[workspace.dependencies]
keyword-analyzer-shared = { path = "shared-lib" }
tokio = { version = "1", features = ["full"] }
axum = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"